[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Chip name found from `probe-rs chip list`
runner = "probe-rs run --chip STM32F303VCTx"

[build]
# Default compilation target:
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"
