name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Rust Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: thumbv7em-none-eabihf

      - name: Install Cargo Dependencies
        run: rustup target add thumbv7em-none-eabihf

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run cargo clippy
        run: cargo clippy --target thumbv7em-none-eabihf -- -D warnings
